#!/usr/bin/perl -w
use strict;
use warnings;
use 5.014;

use Getopt::Long qw( :config bundling );
use Net::Whois::Spec::Lexer;
use Net::Whois::Spec::Validator;
use Net::Whois::Spec::Grammar qw( $grammar );
use Net::Whois::Spec::Types;

my %rules = (
    d => 'Domain Name Object query',
    r => 'Registrar Object query',
    n => 'Name Server Object query',
);

my $opt_header;
my $opt_type;
GetOptions(
        "header|h" => \$opt_header,
        "type|t=s" => \$opt_type,
        );
if (!exists $rules{$opt_type}) {
    die "error: must specify --type " . join('|', keys %rules);
}

my $rule = $rules{$opt_type};
my $text = do { local $/; <STDIN> };

my $lexer = Net::Whois::Spec::Lexer->new($text);

if ($opt_header) {
    my ($token, $token_value) = $lexer->peek_line();
    while ($token eq 'non-empty line' && $token_value =~ /^#/) {
        $lexer->next_line();
        ($token, $token_value) = $lexer->peek_line();
    }
}

my $types = Net::Whois::Spec::Types->new;
my $validator = Net::Whois::Spec::Validator->new(lexer => $lexer, grammar => $grammar, types => $types);

for my $error (@{ $validator->validate($rule) }) {
    say $error;
}
